# Generated by Django 4.1.7 on 2023-03-02 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyReg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=80)),
                ('clocation', models.CharField(max_length=40)),
                ('ctype', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('uname', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=17)),
            ],
        ),
    ]
