# Generated by Django 4.1.7 on 2023-03-03 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=70)),
                ('lname', models.CharField(max_length=70)),
                ('addrs', models.CharField(max_length=190)),
                ('qual', models.CharField(max_length=90)),
                ('email', models.EmailField(max_length=254)),
                ('phno', models.CharField(max_length=12)),
                ('uname', models.CharField(max_length=90)),
                ('pswrd', models.CharField(max_length=29)),
            ],
        ),
    ]
