# Generated by Django 4.1.6 on 2023-04-20 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_userreg'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddVnc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vno', models.IntegerField(max_length=20)),
                ('vname', models.CharField(max_length=30)),
                ('salary', models.IntegerField(max_length=10)),
                ('nop', models.CharField(max_length=29)),
                ('qual', models.CharField(max_length=30)),
                ('compid', models.CharField(max_length=20)),
                ('company', models.CharField(max_length=50)),
                ('filled', models.IntegerField(default=0)),
            ],
        ),
    ]
